version: "3.7"
services:
  app:
    container_name: smooth_test
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # 경로설정
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
